version: '3'
services:
    nginx:
        build: ./docker-images/nginx
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/html
        depends_on:
            - php-fpm

    php-fpm:
        build: ./docker-images/php-fpm
        container_name: php-fpm
        restart: always
        volumes:
            - ./app:/var/www/html
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports: 
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=app
    mysqltest:
        image: mysql:5.7
        container_name: mysqltest
        ports: 
            - "3307:3306"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=app